### ISSUE TITLE
Go through the canvas API library and choose relevant endpoints

### ISSUE THREAD

**Issue by mmbc2008** [mmbc2008/HCI-Project#13]
We need specific endpoints to do with grades and the student being able to see their courses.

**Comment by paulalkh** [comment]
For the courses:
https://canvas.instructure.com/doc/api/courses.html#method.courses.index
- Course Overview: url:GET|/api/v1/courses
- Course Overview for other students: url:GET|/api/v1/users/:user_id/courses
- Teacher or Student: url:GET|/api/v1/courses + enrollment_type
- Final grade for course:  url:GET|/api/v1/courses + total_scores
- Current grade for course: url:GET|/api/v1/courses + current_grading_period_scores
